# my global config
global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

remote_write:
  - url: https://metrics.onemedtest.com/api/v1/write
    remote_timeout: "30s"
    send_exemplars: false
    follow_redirects: true

    write_relabel_configs:
    - action: 'replace'
      target_label: 'source'
      replacement: 'safe_mac_node'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: node-exporter
    static_configs:
      - targets:
          - "cadvisor:8080"

  # - job_name: 'node'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['192.168.56.49:9100']
